config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :noticia
  resources :comentarios
  post 'noticias/comentar' , to: 'noticia#comentar'
  get 'noticias/admin', to: 'noticia#admin'
  get 'noticias/inicio', to: 'noticia#index'
  root 'noticia#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comentario.rb
class Comentario < ApplicationRecord
	belongs_to :noticium
	validates_presence_of :fecha,
	:contenido,
	:nombre
end

app/models/noticium.rb
class Noticium < ApplicationRecord
	has_many :comentarios
	validates_presence_of :fecha,
	 	:bajada, 
	 	:cuerpo,
	 	:titular
	validates_length_of :bajada, maximum: 200
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/noticia_controller.rb
class NoticiaController < ApplicationController
  before_action :set_noticium, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only:[:create, :edit, :update, :destroy, :new]


  # GET /noticia
  # GET /noticia.json
  def index
    @noticia = Noticium.limit(10).order(:fecha).reverse_order
  end

  def comentar
    comentario = params[:comentario]
    n = Noticium.find(comentario[:noticium_id])
    h = {
      fecha: comentario[:fecha],
      contenido: comentario[:contenido],
      noticium: n,
      nombre: comentario[:nombre]
    }
    @comentario = Comentario.create(h)


    respond_to do |format|
      if @comentario.save
        format.html { redirect_to n, notice: 'Comentario was successfully created.' }
      else
        format.html { redirect_to n, notice: 'Imposible comentar, faltan parametros'}
        format.json { render json: @comentario.errors, status: :unprocessable_entity }
      end
    end
  end

  def admin
    @noticia = Noticium.all.order(:fecha).reverse_order
  end


  # GET /noticia/1
  # GET /noticia/1.json
  def show
    #@comentario = Comentario.new
    @comentario = @noticium.comentarios.build
  end

  # GET /noticia/new
  def new
    @noticium = Noticium.new
  end

  # GET /noticia/1/edit
  def edit
  end

  # POST /noticia
  # POST /noticia.json
  def create
    @noticium = Noticium.new(noticium_params)

    respond_to do |format|
      if @noticium.save
        format.html { redirect_to @noticium, notice: 'Noticium was successfully created.' }
        format.json { render :show, status: :created, location: @noticium }
      else
        format.html { render :new }
        format.json { render json: @noticium.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /noticia/1
  # PATCH/PUT /noticia/1.json
  def update
    respond_to do |format|
      h = {
        cuerpo: noticium_params[:cuerpo],
        bajada: noticium_params[:bajada],
        titular: noticium_params[:titular]
      }
      if @noticium.update(h)
        format.html { redirect_to @noticium, notice: 'Noticium was successfully updated.' }
        format.json { render :show, status: :ok, location: @noticium }
      else
        format.html { render :edit }
        format.json { render json: @noticium.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /noticia/1
  # DELETE /noticia/1.json
  def destroy
    @noticium.destroy
    respond_to do |format|
      format.html { redirect_to noticia_url, notice: 'Noticium was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_noticium
      @noticium = Noticium.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def noticium_params
      params.require(:noticium).permit(:fecha, :cuerpo, :bajada, :titular)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/noticia_helper.rb
module NoticiaHelper
end

app/views/comentario/_form.html.erb
<%= form_for @comentario, :url => { :action => "comentar"} do |form| %>

  <%= form.hidden_field :fecha, :value => Date.today %>
  <%= form.hidden_field :noticium_id, :value => @noticium.id %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre, id: :comentario_nombre %>
  </div>

  <div class="field">
    <%= form.label :contenido %>
    <%= form.text_area :contenido, id: :comentario_contenido %>
  </div>



  <div class="actions">
    <%= form.submit 'Comentar'%>
  </div>
<% end %>

app/views/comentario/new.html.erb
<h1>New Comentario</h1>

<%= render 'form', comentario: @comentario %>

<%= link_to 'Back', noticia_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NoticiasApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <h1><%= link_to 'Inicio', noticia_path %></h1>
  <body>
  	<!-- Codigo sacado de https://guides.railsgirls.com/devise -->
  	<p class="navbar-text pull-right">
		<% if user_signed_in? %>
		  Logged in as <strong><%= current_user.email %></strong>.
		  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
		  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
		<% else %>
		  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
		  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
		<% end %>
	</p>
    <%= yield %>
  </body>
</html>

app/views/noticia/_form.html.erb
<%= form_with(model: noticium, local: true) do |form| %>
  <% if noticium.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(noticium.errors.count, "error") %> prohibited this noticium from being saved:</h2>

      <ul>
      <% noticium.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :titular %>
    <%= form.text_field :titular, id: :noticium_titular %>
  </div>

  <%= form.hidden_field :fecha, :value => Date.today %>

  <div class="field">
    <%= form.label :bajada %>
    <%= form.text_area :bajada, id: :noticium_bajada %>
  </div>


  <div class="field">
    <%= form.label :cuerpo %>
    <%= form.text_area :cuerpo, id: :noticium_cuerpo %>
  </div>

  <div class="actions">
    <%= form.submit 'Confirmar'%>
  </div>
<% end %>

app/views/noticia/admin.html.erb
<p id="notice"><%= notice %></p>

<h1>Noticias Administrador</h1>



  
    <% @noticia.each do |noticium| %>
    <table>
      <thead>
        <tr>
          <th>Titular</th>
          <th>Bajada</th>
          <th>Fecha</th>
          <th>Cuerpo</th>
          <th>Comentarios</th>
          <th colspan="3"></th>
        </tr>
      </thead>
    <tbody>
      <tr>
        <td><%= noticium.titular %></td>
        <td><%= noticium.bajada %></td>
        <td><%= noticium.fecha %></td>
        <td><%= noticium.cuerpo.truncate(503) %></td>
        <td><%= noticium.comentarios.count %></td>
        <% if user_signed_in? %>
          <td><%= link_to 'Editar', edit_noticium_path(noticium) %></td>
          <td><%= link_to 'Eliminar', noticium, method: :delete, data: { confirm: '¿Estas seguro que deseas eliminarla?' } %></td>
        <% end %>

        <td><%= link_to 'Leer completa', noticium %></td>
      </tr>
    </tbody>
    </table>
    <% end %>


<br>
<% if user_signed_in? %>
  <%= link_to 'Agregar Noticia', new_noticium_path %>  
<% end %>

app/views/noticia/edit.html.erb
<h1>Editar Noticia</h1>

<%= render 'form', noticium: @noticium %>

<%= link_to 'Show', @noticium %> |
<%= link_to 'Back', noticia_path %>

app/views/noticia/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Noticias</h1>



  
    <% @noticia.each do |noticium| %>
    <table>
      <thead>
        <tr>
          <th>Titular</th>
          <th>Bajada</th>
          <th>Fecha</th>
          <th>Cuerpo</th>
          <th>Comentarios</th>
          <th colspan="3"></th>
        </tr>
      </thead>
    <tbody>
      <tr>
        <td><%= noticium.titular %></td>
        <td><%= noticium.bajada %></td>
        <td><%= noticium.fecha %></td>
        <td><%= noticium.cuerpo.truncate(503) %></td>
        <td><%= noticium.comentarios.count %></td>
        <td><%= link_to 'Leer completa', noticium %></td>
      </tr>
    </tbody>
    </table>
    <% end %>


<br>
<% if user_signed_in? %>
  <%= link_to 'Entrar modo administrador', 'noticias/admin' %> 
<% end %>

app/views/noticia/new.html.erb
<h1>Nueva Noticia</h1>

<%= render 'form', noticium: @noticium %>

<%= link_to 'Back', noticia_path %>

app/views/noticia/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titular:</strong>
  <%= @noticium.titular %>
</p>

<p>
  <strong>Bajada:</strong>
  <%= @noticium.bajada %>
</p>

<p>
  <strong>Fecha:</strong>
  <%= @noticium.fecha %>
</p>

<p>
  <strong>Cuerpo:</strong>
  <%= @noticium.cuerpo %>
</p>


<p>
	<strong>Comentarios:</strong>
</p>
<table>
<% @noticium.comentarios.each do |comentario| %>
	<tr>
    <td><%= comentario.nombre %></td>
		<td><%= comentario.contenido %></td>
		<td><%= comentario.fecha %> </td>
	</tr>
 <% end %>
 </table>

<%= render 'comentario/form', comentario: @comentario %>


<%= link_to 'Back', noticia_path %>